//! Writes a synthetic star field and the catalogue it was generated from, so
//! `scripts/demo.sh` can build an index and solve it with no Gaia mirror, no
//! network and no rig data.
//!
//! The data is synthetic on purpose rather than for convenience: a real index
//! is derived from Gaia DR3 and is CC BY-NC 3.0 IGO, which this repo's MIT
//! licence does not cover (see `docs/data-licence.md`), so no real index can
//! ship here.
//!
//! The generator is the one `tests/cli_solve_success.rs` uses -- reproduced
//! rather than shared, because `psolve-cli` has no `[lib]` target for an
//! example and a test to link against in common.
//!
//! Usage: `synth_field <dir>` writes `<dir>/field.fits` and `<dir>/cat/a.csv`.

use psolve_core::fit::Wcs;

const NX: usize = 640;
const NY: usize = 480;
const SCALE_ARCSEC: f64 = 2.4614;

/// Deterministic hashed scatter, so the demo produces the same field on every
/// machine and a failure is reproducible rather than a coin toss.
fn scatter(i: usize) -> (f64, f64) {
    let mut z = (i as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15);
    let mut next = || {
        z = z.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut x = z;
        x = (x ^ (x >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        x = (x ^ (x >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        x ^ (x >> 31)
    };
    let a = next();
    let b = next();
    ((a >> 11) as f64 / (1u64 << 53) as f64, (b >> 11) as f64 / (1u64 << 53) as f64)
}

/// The truth this field is generated through. `crpix` is `[NX/2, NY/2]`, half
/// a pixel off the true centre in psolve-core's 0-based convention -- harmless
/// here because the catalogue below is generated by pushing pixels through
/// this very WCS, so the offset cancels exactly.
fn truth_wcs(ra0: f64, dec0: f64) -> Wcs {
    let s = SCALE_ARCSEC / 3600.0;
    Wcs { crval: [ra0, dec0], crpix: [NX as f64 / 2.0, NY as f64 / 2.0], cd: [[-s, 0.0], [0.0, s]] }
}

/// A FITS frame with `n` Gaussian stars well clear of the edge margin, plus a
/// CSV catalogue of those same stars' true sky positions under `truth_wcs`.
fn build_fixture(ra0: f64, dec0: f64, n: usize) -> (Vec<u8>, String) {
    let w = truth_wcs(ra0, dec0);
    let margin = 40.0;
    let mut pix = Vec::new();
    for i in 0..n {
        let (u, v) = scatter(i);
        pix.push((margin + u * (NX as f64 - 2.0 * margin), margin + v * (NY as f64 - 2.0 * margin)));
    }

    let mut img = vec![1000f64; NX * NY];
    for (i, v) in img.iter_mut().enumerate() {
        *v += ((i * 2654435761usize) % 97) as f64 * 0.4;
    }
    let sigma = 1.8f64;
    let mut csv = String::from("ra,dec,pmra,pmdec,phot_g_mean_mag\n");
    for (k, &(cx, cy)) in pix.iter().enumerate() {
        let peak = 8000.0 - (k % 20) as f64 * 150.0;
        let r = 5i64;
        for dy in -r..=r {
            for dx in -r..=r {
                let x = cx.round() as i64 + dx;
                let y = cy.round() as i64 + dy;
                if x < 0 || y < 0 || x >= NX as i64 || y >= NY as i64 {
                    continue;
                }
                let ex = x as f64 - cx;
                let ey = y as f64 - cy;
                img[y as usize * NX + x as usize] +=
                    peak * (-(ex * ex + ey * ey) / (2.0 * sigma * sigma)).exp();
            }
        }
        let (ra, dec) = w.pix_to_radec(cx, cy);
        csv.push_str(&format!("{ra:.8},{dec:.8},0,0,{:.2}\n", 12.0 + (k % 10) as f64 * 0.1));
    }

    let cards = [
        "SIMPLE  =                    T".to_string(),
        "BITPIX  =                   16".to_string(),
        "NAXIS   =                    2".to_string(),
        format!("NAXIS1  = {NX:>20}"),
        format!("NAXIS2  = {NY:>20}"),
        "BZERO   =                32768".to_string(),
    ];
    let mut s = String::new();
    for c in &cards {
        s.push_str(&format!("{c:<80}"));
    }
    s.push_str(&format!("{:<80}", "END"));
    while !s.len().is_multiple_of(2880) {
        s.push(' ');
    }
    let mut out = s.into_bytes();
    for v in &img {
        let clamped = v.clamp(0.0, 65535.0) as u16;
        out.extend_from_slice(&((clamped as i32 - 32768) as i16).to_be_bytes());
    }
    while !out.len().is_multiple_of(2880) {
        out.push(0);
    }
    (out, csv)
}

fn main() {
    let dir = match std::env::args().nth(1) {
        Some(d) => std::path::PathBuf::from(d),
        None => {
            eprintln!("usage: synth_field <dir>");
            std::process::exit(2);
        }
    };
    let cat = dir.join("cat");
    std::fs::create_dir_all(&cat).expect("create output dir");
    let (fits, csv) = build_fixture(83.822, -5.391, 60);
    std::fs::write(dir.join("field.fits"), &fits).expect("write field.fits");
    std::fs::write(cat.join("a.csv"), csv).expect("write catalogue");
    println!("{}", dir.display());
}
