//! Every test in `cli_solve.rs` uses `blank_fits` -- a frame with no stars --
//! so the 30-argument `println!` for a successful solve has never actually
//! executed by CI. A future reordering of that block could ship silently
//! broken. This file builds a real matching frame + catalogue through the
//! public CLI and requires `"solved":true` to come back with a WCS near the
//! truth pointing.

use psolve_core::fit::Wcs;
use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::env::current_exe().unwrap();
    p.pop();
    if p.ends_with("deps") {
        p.pop();
    }
    p.join("psolve")
}

fn tmpdir(tag: &str) -> std::path::PathBuf {
    let d = std::env::temp_dir().join(format!("psolve-solve-success-{tag}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

const NX: usize = 640;
const NY: usize = 480;
const SCALE_ARCSEC: f64 = 2.4614;

/// Deterministic hashed scatter -- same generator `psolve-core`'s own
/// synthetic tests use, reproduced here rather than shared across crates so
/// this file stands on its own.
fn scatter(i: usize) -> (f64, f64) {
    let mut z = (i as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15);
    let mut next = || {
        z = z.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut x = z;
        x = (x ^ (x >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        x = (x ^ (x >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        x ^ (x >> 31)
    };
    let a = next();
    let b = next();
    ((a >> 11) as f64 / (1u64 << 53) as f64, (b >> 11) as f64 / (1u64 << 53) as f64)
}

/// `crpix` is `[NX/2, NY/2]`, which in psolve-core's own 0-BASED pixel
/// convention is **half a pixel off** the true image centre (that is
/// `[(NX-1)/2, (NY-1)/2]` -- see `sidecar.rs`'s "CRPIX convention" module
/// doc and the `field.center` fix it came out of). Left as-is deliberately:
/// this is a self-consistent synthetic truth -- the catalogue below is
/// generated by pushing pixels through this very WCS -- so the half-pixel
/// offset cancels exactly, and every tolerance here is orders of magnitude
/// wider than it anyway. Do not read "the exact image centre" off this
/// line; it is the pre-fix convention, kept only because changing it would
/// regenerate the fixture for no gain.
fn truth_wcs(ra0: f64, dec0: f64) -> Wcs {
    let s = SCALE_ARCSEC / 3600.0;
    Wcs { crval: [ra0, dec0], crpix: [NX as f64 / 2.0, NY as f64 / 2.0], cd: [[-s, 0.0], [0.0, s]] }
}

/// A FITS frame with `n` Gaussian stars, well clear of the edge margin, plus
/// a CSV catalogue built from those same stars' true sky positions under
/// `truth_wcs`.
fn build_fixture(ra0: f64, dec0: f64, n: usize) -> (Vec<u8>, String) {
    let w = truth_wcs(ra0, dec0);
    let margin = 40.0;
    let mut pix = Vec::new();
    for i in 0..n {
        let (u, v) = scatter(i);
        pix.push((margin + u * (NX as f64 - 2.0 * margin), margin + v * (NY as f64 - 2.0 * margin)));
    }

    let mut img = vec![1000f64; NX * NY];
    for (i, v) in img.iter_mut().enumerate() {
        *v += ((i * 2654435761usize) % 97) as f64 * 0.4;
    }
    let sigma = 1.8f64;
    let mut csv = String::from("ra,dec,pmra,pmdec,phot_g_mean_mag\n");
    for (k, &(cx, cy)) in pix.iter().enumerate() {
        let peak = 8000.0 - (k % 20) as f64 * 150.0;
        let r = 5i64;
        for dy in -r..=r {
            for dx in -r..=r {
                let x = cx.round() as i64 + dx;
                let y = cy.round() as i64 + dy;
                if x < 0 || y < 0 || x >= NX as i64 || y >= NY as i64 {
                    continue;
                }
                let ex = x as f64 - cx;
                let ey = y as f64 - cy;
                let val = peak * (-(ex * ex + ey * ey) / (2.0 * sigma * sigma)).exp();
                img[y as usize * NX + x as usize] += val;
            }
        }
        let (ra, dec) = w.pix_to_radec(cx, cy);
        csv.push_str(&format!("{ra:.8},{dec:.8},0,0,{:.2}\n", 12.0 + (k % 10) as f64 * 0.1));
    }

    let cards = [
        "SIMPLE  =                    T".to_string(),
        "BITPIX  =                   16".to_string(),
        "NAXIS   =                    2".to_string(),
        format!("NAXIS1  = {NX:>20}"),
        format!("NAXIS2  = {NY:>20}"),
        "BZERO   =                32768".to_string(),
    ];
    let mut s = String::new();
    for c in &cards {
        s.push_str(&format!("{c:<80}"));
    }
    s.push_str(&format!("{:<80}", "END"));
    while !s.len().is_multiple_of(2880) {
        s.push(' ');
    }
    let mut out = s.into_bytes();
    for v in &img {
        let clamped = v.clamp(0.0, 65535.0) as u16;
        let stored = (clamped as i32 - 32768) as i16;
        out.extend_from_slice(&stored.to_be_bytes());
    }
    while !out.len().is_multiple_of(2880) {
        out.push(0);
    }
    (out, csv)
}

/// Build the frame+catalogue fixture and an index from it, and write both to
/// `d`. Returns the frame path and the index path.
fn setup(d: &std::path::Path, ra0: f64, dec0: f64) -> (std::path::PathBuf, std::path::PathBuf) {
    let (fits_bytes, csv) = build_fixture(ra0, dec0, 60);
    let f = d.join("field.fits");
    std::fs::write(&f, &fits_bytes).unwrap();

    let input = d.join("cat");
    std::fs::create_dir_all(&input).unwrap();
    std::fs::write(input.join("a.csv"), csv).unwrap();
    let idx = d.join("t.psidx");
    let o = Command::new(bin())
        .args(["index", "build", "--input"])
        .arg(&input)
        .arg("--out")
        .arg(&idx)
        .args(["--max-mag", "20", "--nside", "64"])
        .output()
        .unwrap();
    assert!(o.status.success(), "index build failed: {}", String::from_utf8_lossy(&o.stderr));
    (f, idx)
}

/// Pull `"crval":[ra,dec]` out of the JSON without a JSON dependency.
fn extract_crval(json: &str) -> Option<(f64, f64)> {
    let key = "\"crval\":[";
    let start = json.find(key)? + key.len();
    let end = json[start..].find(']')? + start;
    let mut parts = json[start..end].split(',');
    let ra: f64 = parts.next()?.trim().parse().ok()?;
    let dec: f64 = parts.next()?.trim().parse().ok()?;
    Some((ra, dec))
}

/// Pull `"field":{"center":{"ra":..,"dec":..}` out of the JSON.
fn extract_field_center(json: &str) -> Option<(f64, f64)> {
    let key = "\"center\":{\"ra\":";
    let start = json.find(key)? + key.len();
    let rest = &json[start..];
    let ra_end = rest.find(',')?;
    let ra: f64 = rest[..ra_end].trim().parse().ok()?;
    let after_comma = &rest[ra_end + 1..];
    let dec_key = "\"dec\":";
    let dec_start = after_comma.find(dec_key)? + dec_key.len();
    let dec_rest = &after_comma[dec_start..];
    let dec_end = dec_rest.find('}')?;
    let dec: f64 = dec_rest[..dec_end].trim().parse().ok()?;
    Some((ra, dec))
}

#[test]
fn a_matching_frame_solves_and_reports_the_true_pointing() {
    let d = tmpdir("basic");
    let (ra0, dec0) = (150.0, -10.0);
    let (f, idx) = setup(&d, ra0, dec0);

    let o = Command::new(bin())
        .args(["solve"])
        .arg(&f)
        .arg("--index")
        .arg(&idx)
        .args(["--hint", &format!("{ra0},{dec0}")])
        .args(["--scale", &SCALE_ARCSEC.to_string()])
        // Well above the painted stars' peaks: this fixture's flat-topped
        // Gaussian rounding could otherwise share >=8 pixels at the image
        // maximum and trip the repeated-maximum saturation heuristic.
        .args(["--saturation", "60000"])
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&o.stdout).to_string();
    assert_eq!(
        o.status.code(),
        Some(0),
        "stderr: {}\nstdout: {stdout}",
        String::from_utf8_lossy(&o.stderr)
    );

    assert!(stdout.contains("\"solved\":true"), "stdout: {stdout}");
    for key in [
        "\"wcs\"", "\"crval\"", "\"crpix\"", "\"cd\"", "\"cdelt\"", "\"pc\"", "\"parity\"",
        "\"field\"", "\"fov_deg\"", "\"scale_arcsec\"", "\"orientation_pa\"", "\"stars\"",
        "\"fit\"", "\"quality\"", "\"epoch\"", "\"index\"", "\"timings_ms\"", "\"build\"",
    ] {
        assert!(stdout.contains(key), "missing {key} in {stdout}");
    }
    assert!(!stdout.contains("NaN") && !stdout.contains(":inf"), "invalid JSON tokens: {stdout}");

    // `build` (spec §7.2) is the field a consumer should key a
    // changed-analyser check on -- `psolve` is only the crate version and
    // does not move on every behaviour change. It must be present and
    // non-empty on a real, git-backed build of this repo.
    let build_key = "\"build\":\"";
    let build_start = stdout.find(build_key).expect("build field present") + build_key.len();
    let build_end = stdout[build_start..].find('"').expect("build value terminates") + build_start;
    assert!(
        !stdout[build_start..build_end].is_empty(),
        "build must be non-empty on a real build: {stdout}"
    );

    let (crval_ra, crval_dec) = extract_crval(&stdout).expect("crval should parse");
    assert!((crval_ra - ra0).abs() < 0.01, "crval ra {crval_ra} vs truth {ra0}");
    assert!((crval_dec - dec0).abs() < 0.01, "crval dec {crval_dec} vs truth {dec0}");
}

/// The bug this pins: `field.center` used to be computed as
/// `wcs.pix_to_radec(crpix)`, which by definition equals `crval` -- and
/// `fit_tan` pins `crval` to the caller's `--hint`, not to where the frame
/// actually points. So a solve with a hint that is off from the true frame
/// centre used to report the HINT back as "field.center", making an accurate
/// solve look like it disagreed with the hint by exactly the hint's own
/// error.
///
/// This fixture's true frame centre is `(ra0, dec0)` (the fixture is built
/// from `truth_wcs(ra0, dec0)` with `crpix` at the exact image centre). The
/// `--hint` passed to the command is deliberately offset from that. A
/// correct `field.center` must land near the true centre and therefore
/// clearly away from the hint; the old code landed exactly on the hint.
#[test]
fn field_center_reports_the_image_centre_not_the_hint() {
    let d = tmpdir("field-center");
    let (ra0, dec0) = (150.0, -10.0);
    let (f, idx) = setup(&d, ra0, dec0);

    // A deliberate pointing-hint error, well inside the default search
    // radius but large relative to this fixture's ~0.03 deg field width --
    // comparable in kind (if not degree) to the arcsecond-scale hint error
    // that exposed this bug on real data.
    let (hint_ra, hint_dec) = (ra0 + 0.05, dec0 + 0.03);

    let o = Command::new(bin())
        .args(["solve"])
        .arg(&f)
        .arg("--index")
        .arg(&idx)
        .args(["--hint", &format!("{hint_ra},{hint_dec}")])
        .args(["--scale", &SCALE_ARCSEC.to_string()])
        .args(["--saturation", "60000"])
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&o.stdout).to_string();
    assert_eq!(
        o.status.code(),
        Some(0),
        "stderr: {}\nstdout: {stdout}",
        String::from_utf8_lossy(&o.stderr)
    );
    assert!(stdout.contains("\"solved\":true"), "stdout: {stdout}");

    let (crval_ra, crval_dec) = extract_crval(&stdout).expect("crval should parse");
    let (center_ra, center_dec) = extract_field_center(&stdout).expect("field.center should parse");

    // crval must still equal the hint -- that part of the design (CRVAL
    // pinned to the tangent point) is correct and unchanged.
    assert!((crval_ra - hint_ra).abs() < 0.01, "crval ra {crval_ra} vs hint {hint_ra}");
    assert!((crval_dec - hint_dec).abs() < 0.01, "crval dec {crval_dec} vs hint {hint_dec}");

    // field.center must land near the TRUE frame centre...
    assert!(
        (center_ra - ra0).abs() < 0.01,
        "field.center ra {center_ra} should be near the true centre {ra0}, not the hint"
    );
    assert!(
        (center_dec - dec0).abs() < 0.01,
        "field.center dec {center_dec} should be near the true centre {dec0}, not the hint"
    );

    // ...which is exactly the bug: field.center must NOT simply echo crval
    // (the hint) back. This is the assertion that would have failed before
    // the fix, since the offset is well above both tolerances above.
    assert!(
        (center_ra - crval_ra).abs() > 0.01 || (center_dec - crval_dec).abs() > 0.01,
        "field.center ({center_ra},{center_dec}) must differ from crval/hint \
         ({crval_ra},{crval_dec}) -- reporting the hint back is the bug"
    );
}

#[test]
fn saturation_is_wired_through_to_the_extractor() {
    // A --saturation well below the painted stars' peaks must reject every
    // real star as clipped, proving the flag actually reaches core rather
    // than being accepted on the command line and silently ignored.
    let d = tmpdir("saturation-plumbing");
    let (ra0, dec0) = (150.0, -10.0);
    let (f, idx) = setup(&d, ra0, dec0);

    let o = Command::new(bin())
        .args(["solve"])
        .arg(&f)
        .arg("--index")
        .arg(&idx)
        .args(["--hint", &format!("{ra0},{dec0}")])
        .args(["--scale", &SCALE_ARCSEC.to_string()])
        .args(["--saturation", "100"]) // far below the painted stars' peaks
        .output()
        .unwrap();
    let stdout = String::from_utf8_lossy(&o.stdout);
    assert!(
        stdout.contains("\"solved\":false"),
        "an artificially low --saturation must reject the real stars: {stdout}"
    );
}
